import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronLeft,ChevronRight,Focus,Info,Layers3,Pause,Play,RotateCcw,RotateCw,Route,Search,Tags,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SEASON_END,SYSTEMS,TOUR,EXPLANATIONS,explanation,phenology,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,labels:false,day:SEASON_END};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null),[tourStep,setTourStep]=useState(-1),[growing,setGrowing]=useState(false);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setTourStep(-1);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas-maturity.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{if(!growing)return;const id=setInterval(()=>{setState(s=>{const nd=Math.min(SEASON_END,s.day+.55);if(nd>=SEASON_END)setGrowing(false);return {...s,day:nd};});},45);return()=>clearInterval(id);},[growing]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['fibrous root system','main culm','flag leaves','leaf blades','panicles (inflorescences)','grains (spikelets)'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setTourStep(-1);setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setTourStep(-1);setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setTourStep(-1);setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const tourSteps=useMemo(()=>atlas?TOUR.filter(t=>atlas.concepts.some(c=>c.id===t.concept&&c.elements.length>0)):[],[atlas]);
 const applyTour=(i:number)=>{const step=tourSteps[i];const c=atlas?.concepts.find(x=>x.id===step?.concept);if(!c)return;setGrowing(false);setTourStep(i);setPanel(null);setDetails(false);setChosen(c);setState(s=>({...s,selected:c.elements,isolate:true,explode:0,rotate:false,labels:false,day:SEASON_END}));};
 const endTour=()=>{setTourStep(-1);setChosen(null);setDetails(false);setState(s=>({...s,selected:[],isolate:false}));};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE ANATOMY</div><h1>Rice Plant Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'—'} modeled organs <span>·</span> Oryza sativa</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={tourStep>=0?'active':''} disabled={!tourSteps.length} onClick={()=>tourStep>=0?endTour():applyTour(0)} aria-label="Guided tour"><Route size={18}/><span>Tour</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===3&&['Stem','Sheath','Leaves'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['Stem','Sheath','Leaves']}))}>Shoot</Button><Button variant="ghost" aria-pressed={state.visible.length===2&&['Panicle','Grain'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['Panicle','Grain']}))}>Panicle</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='Root'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['Root']}))}>Roots</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Root, Leaf, Panicle…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" disabled={state.explode>.05} aria-label="Toggle figure labels" title="Figure labels" className={state.labels?'active':''} onClick={()=>{setDetails(false);setState(s=>({...s,labels:!s.labels,isolate:false,selected:[]}));}}><Tags size={17}/></Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  {tourStep<0&&<div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':`DAY ${Math.round(state.day)} · ${phenology(state.day).toUpperCase()}`}</span><span className="caption-line"/></div>}
  {tourStep<0&&<div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="dock-controls">
   <div className="grow-control"><div className="explode-label"><label id="grow-label">Days after sowing</label><span className="phenology-tag">{phenology(state.day)}</span><output>{Math.round(state.day)}<span>d</span></output></div><div className="grow-row"><Button variant="ghost" className="grow-play" aria-label={growing?'Pause growth':'Grow the plant'} title={growing?'Pause growth':'Grow from sowing'} onClick={()=>{if(growing)setGrowing(false);else{setDetails(false);setPanel(null);setState(s=>({...s,day:s.day>=SEASON_END-1?0:s.day,isolate:false,explode:0,rotate:false}));setGrowing(true);}}}>{growing?<Pause size={15}/>:<Play size={15}/>}</Button><Slider aria-labelledby="grow-label" min={0} max={SEASON_END} step={1} disabled={state.explode>.05} value={[state.day]} onValueChange={v=>{setGrowing(false);setState(s=>({...s,day:Array.isArray(v)?v[0]:v,rotate:s.rotate}));}}/></div></div>
   <div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><button type="button" onClick={()=>setState(s=>({...s,explode:0,rotate:false}))}>Assembled</button><button type="button" onClick={()=>setState(s=>({...s,explode:1,view:'front',selected:[],isolate:false,rotate:false}))}>Every piece</button></div></div>
  </div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>}
  {tourStep>=0&&tourSteps[tourStep]&&<div className="tour-card glass" role="dialog" aria-label="Guided tour">
   <div className="eyebrow">GUIDED TOUR · {tourStep+1} / {tourSteps.length}</div>
   <h2>{tourSteps[tourStep].title}</h2>
   <p>{tourSteps[tourStep].text}</p>
   <div className="tour-actions"><Button variant="ghost" disabled={tourStep===0} onClick={()=>applyTour(tourStep-1)}><ChevronLeft size={16}/>Back</Button>{tourStep<tourSteps.length-1?<Button className="tour-next" onClick={()=>applyTour(tourStep+1)}>Next<ChevronRight size={16}/></Button>:<Button className="tour-next" onClick={endTour}>Finish</Button>}<Button variant="ghost" className="tour-exit" aria-label="End tour" onClick={endTour}><X size={16}/></Button></div>
  </div>}
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'6'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span>{state.selected.length===1&&selected?.stats&&Object.entries(selected.stats).map(([k,v])=><span key={k}>{k}<strong>{v}</strong></span>)}</div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="#" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button>{selectedParts.length>1&&<Button variant="ghost" className="secondary-action" onClick={()=>setState(s=>({...s,isolate:true,explode:s.isolate&&s.explode>.5?0:1,rotate:false,labels:false}))}>{state.isolate&&state.explode>.5?'Reassemble pieces':`Separate ${selectedParts.length} pieces`}</Button>}<Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false,explode:0}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A rice plant, revealed.</SheetTitle><SheetDescription>A procedural Oryza sativa at grain filling, organ by organ.</SheetDescription><div className="about-copy"><p><strong>Oryza sativa · Procedural model</strong><br/>A functional-structural model of a single rice plant at the grain-filling stage: a tillering crown with eight culms, wrapping leaf sheaths, arching blades, nodding panicles with individually modeled grains, and a fibrous root system.</p><p>Every organ is a separately selectable mesh, grouped into six botanical systems. Proportions and architecture follow the real plant, but this is a conceptual model generated in code — not a scan of a specimen.</p><h3>Source</h3><p>Geometry generated by the included FSPM script (generate_fspm_rice.py). Viewer adapted from the open-source Human Atlas.</p></div></SheetContent></Sheet>
 </main>;
}
